import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Lang = 'en' | 'ru';

interface LangStore {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

export const useLang = create<LangStore>()(
  persist(
    (set) => ({
      lang: 'en',
      setLang: (lang) => set({ lang }),
    }),
    { name: 'video-pipeline-lang' },
  ),
);

const translations: Record<string, Record<Lang, string>> = {
  // Sidebar
  'nav.dashboard': { en: 'Dashboard', ru: 'Главная' },
  'nav.create': { en: 'Create Video', ru: 'Создать видео' },
  'nav.videos': { en: 'My Videos', ru: 'Мои видео' },
  'nav.scenarios': { en: 'Scenarios', ru: 'Сценарии' },
  'nav.publishing': { en: 'Publishing', ru: 'Публикация' },
  'nav.settings': { en: 'Settings', ru: 'Настройки' },
  'nav.collapse': { en: 'Collapse', ru: 'Свернуть' },

  // Dashboard
  'dashboard.title': { en: 'Dashboard', ru: 'Главная' },
  'dashboard.subtitle': { en: 'Overview of your video pipeline', ru: 'Обзор вашего видеоконвейера' },
  'dashboard.newVideo': { en: '+ New Video', ru: '+ Новое видео' },
  'dashboard.totalVideos': { en: 'Total Videos', ru: 'Всего видео' },
  'dashboard.budgetSpent': { en: 'Budget Spent', ru: 'Расход бюджета' },
  'dashboard.published': { en: 'Published', ru: 'Опубликовано' },
  'dashboard.activeJobs': { en: 'Active Jobs', ru: 'Активные задачи' },
  'dashboard.generatingNow': { en: 'generating now', ru: 'генерируется сейчас' },
  'dashboard.ofLimit': { en: 'of {0} limit', ru: 'из {0} лимита' },
  'dashboard.activeGenerations': { en: 'Active Generations', ru: 'Активные генерации' },
  'dashboard.noActiveJobs': { en: 'No active generations', ru: 'Нет активных генераций' },
  'dashboard.recentVideos': { en: 'Recent Videos', ru: 'Последние видео' },
  'dashboard.viewAll': { en: 'View all →', ru: 'Все видео →' },
  'dashboard.noVideos': { en: 'No videos yet. Create your first one!', ru: 'Пока нет видео. Создайте первое!' },
  'dashboard.generating': { en: 'Generating...', ru: 'Генерация...' },

  // Create Video
  'create.title': { en: 'Create Video', ru: 'Создать видео' },
  'create.subtitle': { en: 'Configure and launch a new generation', ru: 'Настройте и запустите генерацию' },
  'create.contentType': { en: 'Content Type', ru: 'Тип контента' },
  'create.fruitSoap': { en: 'Fruit Soap Opera', ru: 'Семейка Ягодок' },
  'create.characterRemix': { en: 'Character Remix', ru: 'Ремикс персонажей' },
  'create.mascot': { en: 'Business Mascot', ru: 'Бизнес-маскот' },
  'create.custom': { en: 'Custom', ru: 'Свой сценарий' },
  'create.fruitSoapDesc': { en: 'Family fruit drama series', ru: 'Семейная драма фруктов' },
  'create.characterRemixDesc': { en: 'Famous chars in viral contexts', ru: 'Известные персонажи в вирусных контекстах' },
  'create.mascotDesc': { en: 'Custom mascots for businesses', ru: 'Маскоты для бизнеса' },
  'create.customDesc': { en: 'Build from scratch', ru: 'Создать с нуля' },
  'create.scenes': { en: 'Scenes', ru: 'Сцены' },
  'create.addScene': { en: '+ Add Scene', ru: '+ Добавить сцену' },
  'create.imagePrompt': { en: 'Image Prompt', ru: 'Промпт для изображения' },
  'create.voiceoverText': { en: 'Voiceover Text', ru: 'Текст озвучки' },
  'create.describeImage': { en: 'Describe the image...', ru: 'Опишите изображение...' },
  'create.narratorSays': { en: 'What the narrator says...', ru: 'Что говорит диктор...' },
  'create.sceneName': { en: 'Scene name...', ru: 'Название сцены...' },
  'create.generatingScenario': { en: 'Generating scenario...', ru: 'Генерация сценария...' },
  'create.estimatedCost': { en: 'Estimated Cost', ru: 'Примерная стоимость' },
  'create.remaining': { en: '{0} remaining', ru: 'Остаток: {0}' },
  'create.generateVideo': { en: 'Generate Video', ru: 'Сгенерировать видео' },
  'create.generating': { en: 'Generating...', ru: 'Генерация...' },

  // Advanced Settings
  'settings.modelSettings': { en: 'Model Settings', ru: 'Настройки моделей' },
  'settings.imageModel': { en: 'Image Model', ru: 'Модель изображений' },
  'settings.videoModel': { en: 'Video Model', ru: 'Модель видео' },
  'settings.voiceTts': { en: 'Voice & TTS', ru: 'Голос и TTS' },
  'settings.voice': { en: 'Voice', ru: 'Голос' },
  'settings.subtitles': { en: 'Subtitles', ru: 'Субтитры' },
  'settings.subtitlesDesc': { en: 'Subtitles are automatically generated from voiceover text and burned into the final video.', ru: 'Субтитры автоматически генерируются из текста озвучки и вшиваются в финальное видео.' },
  'settings.autoGenerated': { en: 'Auto-generated', ru: 'Автоматически' },
  'settings.advancedSettings': { en: 'Advanced Settings', ru: 'Расширенные настройки' },
  'settings.modelParams': { en: 'Model Parameters', ru: 'Параметры модели' },
  'settings.available': { en: 'available', ru: 'доступно' },
  'settings.customized': { en: 'customized', ru: 'изменено' },
  'settings.loadingParams': { en: 'Loading model parameters...', ru: 'Загрузка параметров модели...' },
  'settings.verify': { en: 'Verify', ru: 'Проверить' },

  // Videos
  'videos.title': { en: 'My Videos', ru: 'Мои видео' },
  'videos.subtitle': { en: 'Browse and manage your videos', ru: 'Просмотр и управление видео' },
  'videos.noVideos': { en: 'No videos yet', ru: 'Пока нет видео' },
  'videos.allTypes': { en: 'All types', ru: 'Все типы' },
  'videos.allStatuses': { en: 'All statuses', ru: 'Все статусы' },
  'videos.status.pending': { en: 'Pending', ru: 'Ожидание' },
  'videos.status.running': { en: 'Running', ru: 'Генерация' },
  'videos.status.completed': { en: 'Completed', ru: 'Готово' },
  'videos.status.failed': { en: 'Failed', ru: 'Ошибка' },
  'videos.status.draft': { en: 'Draft', ru: 'Черновик' },
  'videos.status.published': { en: 'Published', ru: 'Опубликовано' },

  // Video Detail
  'videoDetail.backToVideos': { en: 'Back to Videos', ru: 'Назад к видео' },
  'videoDetail.delete': { en: 'Delete', ru: 'Удалить' },
  'videoDetail.confirmDelete': { en: 'Confirm delete?', ru: 'Подтвердить удаление?' },
  'videoDetail.publish': { en: 'Publish', ru: 'Опубликовать' },
  'videoDetail.cost': { en: 'Cost', ru: 'Стоимость' },
  'videoDetail.created': { en: 'Created', ru: 'Создано' },
  'videoDetail.completed': { en: 'Completed', ru: 'Завершено' },
  'videoDetail.scenes': { en: 'Scenes', ru: 'Сцены' },
  'videoDetail.publications': { en: 'Publications', ru: 'Публикации' },
  'videoDetail.noPublications': { en: 'Not published yet', ru: 'Пока не опубликовано' },

  // Scenarios
  'scenarios.title': { en: 'Scenarios', ru: 'Сценарии' },
  'scenarios.subtitle': { en: 'Manage reusable scenario templates', ru: 'Управление шаблонами сценариев' },
  'scenarios.generate': { en: 'Generate from Template', ru: 'Сгенерировать из шаблона' },
  'scenarios.use': { en: 'Use', ru: 'Использовать' },
  'scenarios.noScenarios': { en: 'No scenarios yet', ru: 'Пока нет сценариев' },
  'scenarios.scenes': { en: 'scenes', ru: 'сцен' },
  'scenarios.showConfig': { en: 'Show config', ru: 'Показать конфиг' },
  'scenarios.hideConfig': { en: 'Hide config', ru: 'Скрыть конфиг' },

  // Publishing
  'publishing.title': { en: 'Publishing', ru: 'Публикация' },
  'publishing.subtitle': { en: 'Manage platform connections', ru: 'Управление подключениями к платформам' },
  'publishing.platforms': { en: 'Platforms', ru: 'Платформы' },
  'publishing.connected': { en: 'Connected', ru: 'Подключено' },
  'publishing.notConfigured': { en: 'Not configured', ru: 'Не настроено' },
  'publishing.log': { en: 'Publication Log', ru: 'Журнал публикаций' },
  'publishing.noPublications': { en: 'No publications yet', ru: 'Пока нет публикаций' },

  // Settings page
  'settingsPage.title': { en: 'Settings', ru: 'Настройки' },
  'settingsPage.subtitle': { en: 'Global configuration', ru: 'Глобальная конфигурация' },
  'settingsPage.apiKeys': { en: 'API Keys', ru: 'API ключи' },
  'settingsPage.replicateToken': { en: 'Replicate API Token', ru: 'Токен Replicate API' },
  'settingsPage.tokenConfigured': { en: 'Token configured', ru: 'Токен настроен' },
  'settingsPage.enterNewToken': { en: 'Enter new token to replace...', ru: 'Введите новый токен...' },
  'settingsPage.defaultModels': { en: 'Default Models', ru: 'Модели по умолчанию' },
  'settingsPage.budget': { en: 'Budget', ru: 'Бюджет' },
  'settingsPage.budgetLimit': { en: 'Budget Limit ($)', ru: 'Лимит бюджета ($)' },
  'settingsPage.spent': { en: 'Spent', ru: 'Потрачено' },
  'settingsPage.remaining': { en: 'Remaining', ru: 'Остаток' },
  'settingsPage.output': { en: 'Output', ru: 'Вывод' },
  'settingsPage.outputDir': { en: 'Output Directory', ru: 'Директория вывода' },
  'settingsPage.saveSettings': { en: 'Save Settings', ru: 'Сохранить настройки' },
  'settingsPage.saved': { en: 'Settings saved!', ru: 'Настройки сохранены!' },
  'settingsPage.language': { en: 'Language', ru: 'Язык' },
};

export function t(key: string, ...args: any[]): string {
  const lang = useLang.getState().lang;
  let text = translations[key]?.[lang] ?? translations[key]?.en ?? key;
  args.forEach((arg, i) => {
    text = text.replace(`{${i}}`, String(arg));
  });
  return text;
}

export function useT() {
  const lang = useLang((s) => s.lang);
  return (key: string, ...args: any[]): string => {
    let text = translations[key]?.[lang] ?? translations[key]?.en ?? key;
    args.forEach((arg, i) => {
      text = text.replace(`{${i}}`, String(arg));
    });
    return text;
  };
}
